WEBSOCKET ws://localhost:8080/app/kzapg79rumofutkwh48h?protocol=7&client=js&version=8.4.0&flash=false
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
    "message": "Send when the WebSocket connection is opened"
}
=== wait-for-server
{
    "message": "Wait for the server message and send the current message as response"
}
===
{
    "message": "Send after previous message without waiting for the server message"
}

###
